language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install: npm install -g grunt-cli
install: npm install
script:
  - grunt test
  - grunt coffeelint
after_script: grunt coveralls
notifications:
  email: false
